int kraw_roast(char **args)
{
    (void)args;
    const char *roasts[] = {
        "404: Intelligence Not Found.",
        "Your code compiles by pure luck.",
        "Even Stack Overflow gave up on you.",
        "You make syntax errors in pseudocode.",
        "Your debugger deserves a salary raise.",
        "Your code has trust issues with semicolons.",
        "Your keyboard deserves better.",
        "Git wants to revert your existence.",
        "Your commits are crime scenes.",
        "The compiler sighed before compiling.",
        "Segmentation fault: user not found.",
        "You put the 'bug' in debugging.",
        "Your code is held together by hope.",
        "You optimize bugs instead of code.",
        "Even AI needs coffee after reading your code.",
        "Your indentation started a civil war.",
        "Your variables have identity crises.",
        "Your loops have commitment issues.",
        "Your recursion called for help.",
        "The garbage collector refused your code.",
        "You invented infinite loading.",
        "The CPU filed a complaint.",
        "Your RAM wants therapy.",
        "Your Wi-Fi disconnects out of embarrassment.",
        "Even Notepad judges your code.",
        "You make TODOs permanent.",
        "Your comments are fiction.",
        "Your codebase is an archaeological site.",
        "You debug with prayers.",
        "The compiler deserves hazard pay.",
        "You and merge conflicts are best friends.",
        "Your code runs... away.",
        "Your functions have abandonment issues.",
        "Your pointers point to disappointment.",
        "You forgot to free your memory... literally.",
        "Your stack overflowed emotionally.",
        "Your arrays are out of bounds, just like your confidence.",
        "Even printf is confused.",
        "Your code works only on your machine.",
        "Undefined behavior defines your life.",
        "You don't write bugs, you breed them.",
        "Your code has more patches than a pirate ship.",
        "Even the rubber duck walked away.",
        "Your IDE keeps autosaving disasters.",
        "The compiler is your biggest fan—it sees you every day.",
        "You treat warnings like decorations.",
        "You have a PhD in overthinking.",
        "Your calculator needs a calculator.",
        "You lost an argument with a semicolon.",
        "You can break Hello World.",
        "Your homework fears you.",
        "Your notebook is just expensive scratch paper.",
        "Even your pencil wants retirement.",
        "Your grades are playing hide and seek.",
        "You study like it's optional DLC.",
        "Your exam paper cried first.",
        "You speedrun forgetting.",
        "Your alarm clock has trust issues.",
        "You revise by staring at the book.",
        "Even the textbook gave up explaining.",
        "You highlighted the whole chapter.",
        "Your notes are modern art.",
        "You memorize Wi-Fi passwords better than formulas.",
        "You and deadlines have a toxic relationship.",
        "Your calculator deserves an apology.",
        "Your brain runs in power-saving mode.",
        "You read one page and call it productive.",
        "Your attendance is mythical.",
        "Your handwriting needs subtitles.",
        "Your exam strategy is 'good luck'.",
        "You brought confidence instead of preparation.",
        "Google misses you during exams.",
        "Your pen writes excuses better than answers.",
        "You blink and forget everything.",
        "You study tomorrow every day.",
        "Even autocorrect can't fix your spelling.",
        "Your backpack carries books you never open.",
        "You prepare for exams after the exam.",
        "Your motivation is always buffering.",
        "Your focus left the chat.",
        "You'd lose a race against a loading bar.",
        "You couldn't pour water out of a boot with instructions.",
        "You trip over wireless signals.",
        "You're proof that confidence isn't knowledge.",
        "You bring a spoon to a knife fight.",
        "You lose arguments to mirrors.",
        "Even your shadow walks faster.",
        "You'd get lost in a straight hallway.",
        "You couldn't organize a desktop.",
        "You procrastinate professionally.",
        "Your luck has airplane mode on.",
        "You make easy mode look difficult.",
        "You're the reason shampoo has instructions.",
        "Your brain hit snooze.",
        "Even NPCs have better decision making.",
        "You'd lose hide and seek with yourself.",
        "Your common sense is on vacation.",
        "You're running on 1% battery.",
        "Even your excuses need debugging.",
        "Achievement unlocked: Confused Successfully.",
        "Mission failed successfully.",
        "You almost had a good idea."};
    int n = sizeof(roasts) / sizeof(roasts[0]);
    printf("%s\n", roasts[rand() % n]);
    return 1;
}